name: Deploy to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Upload S3
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./build
          destination_dir: ""
        